Optimized Scheduling
tathagatasrimani/codesign pull request #61
Opened 2024-05-08 19:51 UTC by arjnpandey

2024-06-05 22:10 UTC, fazerlicourice7 requested changes

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +import cvxpy as cp
add a blank line below

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +import heapq
move heapq above with other 3rd party libs

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +        # curr_var.name = node[0]
del this

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +        # constraints.append(curr_var[1] >= 0)
del this

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +    # nx.set_node_attributes(graph, graph_nodes)
del this

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +        # curr_reg_count = {'Regs': 0, 'Add': 0, 'Mult': 0, 'Buf': 0, 'Eq': 0, 'stall': 0}
del this

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +        # curr_reg_count[graph.nodes[start_node]['function']] += 1
del this

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +            # curr_reg_count[graph.nodes[curr_node]['function']] += 1
del this

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +        # print(curr_reg_count)
del this

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +    # obj = cp.Minimize(all_nodes)
del

2024-06-05 22:10 UTC, fazerlicourice7 commented on src/schedule.py
> +def schedule(graph, hw_element_counts):
rename to sdc_schedule.
and call sdc_schedule from simulator and symbolic_simulator

2024-06-08 21:01 UTC, arjnpandey commented on src/schedule.py
> +import heapq
done

2024-06-25 16:38 UTC, fazerlicourice7 approved these changes

2024-06-25 16:38 UTC, merged